language: scala
scala:
  - 2.12.1
  - 2.11.8

sudo: false

script: sbt ++$TRAVIS_SCALA_VERSION test

before_install:
   - rvm install 2.2.0
   # This is necessary to install fluentd dependencies
   - rvm use 2.2.0
   - gem install fluentd -v 0.14.21

jdk:
 - oraclejdk8
